### ISSUE TITLE
Query:- How to set my custom theme to react-menu

### ISSUE THREAD

**Issue by aditya-padhi-kbl** [szhsin/react-menu#659]
React/React-dom version: 16.11.0
React-Menu version: 2.3.4

Hi,

Thank-you for this awesome component.  I have a short query regarding theming.  Please let me know if you have any documentation which will help me to set-up my custom theming on react-menu component.

Kind Regards,
Aditya

**Comment by szhsin** [comment]
Hi @aditya-padhi-kbl 
The menu components are unstyled by nature, so the theming method is very flexible and will largely depend on the stying technique used in your project.

For example, when using styled-components, you could consult their theming page for recommended usage https://styled-components.com/docs/advanced#theming

If you use CSS or Sass, `Menu` has a `theming` prop which can be used to add a class selector on the root menu container node.
```jsx
<Menu theming={isDark ? "dark" : "light"}>
    <MenuItem>Cut</MenuItem>
    <MenuItem>Copy</MenuItem>
    <MenuItem>Paste</MenuItem>
</Menu>
```
then in the css file:
```css
.szh-menu__item {
  color: black;
  background-color: white;
}

.szh-menu-container--theme-dark .szh-menu__item {
  color: white;
  background-color: black;
}
```
